### PR TITLE
feat(site): make site interactive

### PR DESCRIPTION
**Pull request by nfischer**
The site will now generate a new AST with every key-press, similar to how my [shelljs-transpiler project](https://github.com/nfischer/shelljs-transpiler) works. I think it makes things a bit easier to try out.

I've also added a button to the README which links directly to the site, so it's easier to find.

I saw a bug where the alert would initially be displayed, so I fixed that via CSS. If you want a different fix, feel free to modify it as you see fit.

Cheers!

### CODE REVIEW

**Comment by parro-it** [comment]
Awesome work! I wonder if it could be better to clear the AST element in case of syntax error.
Actually if you edit the code in a way that introduce invalid syntax, the old AST is kept on the right box.

**Comment by nfischer** [comment]
As I see it, it isn't necessary. The error alert on the left indicates that it was a failed parse. The AST on the right, if anything, might be useful for showing at what point the parse failed. That's just an idea though, I could see advantages to clearing out the AST.

One nice thing about [ohm](https://github.com/cdglabs/ohm) is that it shows the exact point in the input a parse fails, which we could use to indicate syntax errors to a user. I don't know if Jison supports anything like this, but if so, then I agree that clearing the AST would be most intuitive.

**Comment by parro-it** [comment]
> As I see it, it isn't necessary. The error alert on the left indicates that it was a failed parse. The AST on the right, if anything, might be useful for showing at what point the parse failed. That's just an idea though, I could see advantages to clearing out the AST.

Yes, I see your point, let's go that way!

> One nice thing about ohm is that it shows the exact point in the input a parse fails, which we could use to indicate syntax errors to a user. I don't know if Jison supports anything like this, but if so, then I agree that clearing the AST would be most intuitive.

Actually jison only insert the line number on its syntax errors, but I think we could find a hack to make it emit the column number too.

**Comment by nfischer** [comment]
> Actually jison only insert the line number on its syntax errors, but I think we could find a hack to make it emit the column number too.

Nice! Line number is still a great start! If we want to use [codemirror]() as the site's editor (It's nice, but it's a bit of work to set up), then this would be very easy to indicate parse errors on the particular line. Would this break for continuation lines? I can't remember if we handle continuation lines before parsing or not.

```sh
echo \
hi \
there # is this line 1 or line 3 according to jison?
```

**Comment by piranna** [comment]
> echo \ hi \ there # is this line 1 or line 3 according to jison?

I think it should be line 3.

**Comment by parro-it** [comment]
Yes, line continuations are handled

**Comment by parro-it** [comment]
And using codemirror would be great!

**Pull request merged**
